wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1714477071.000827
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.9.19
      5: 0.13.3
      6: 4.40.1
      8:
      - 1
      - 5
